openapi: 3.0.0

info:
  description: |
    An open-source API for connecting Resellers and Booking Platforms.

    The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in [BCP 14](https://tools.ietf.org/html/bcp14) [RFC 2119](https://tools.ietf.org/html/rfc2119) [RFC 8174](https://tools.ietf.org/html/rfc8174) when, and only when, they appear in all capitals, as shown here.
  version: "1.0.0-alpha"
  title: 'Open Connectivity for Tourism (OCTo) API'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /suppliers:
    get:
      tags:
        - Suppliers
      summary: 'Returns a list of suppliers and associated contact details.'
      description: |
        This list MAY be limited based on the suppliers that the authenticated user has been granted access to.
      operationId: 'suppliers'
      responses:
        '200':
          description: |
            List of suppliers with details.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Supplier'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /suppliers/{supplierId}/products:
    get:
      tags:
        - Products
      summary: 'Returns a list of products for a specific supplier.'
      description: |
        **WARNING: this endpoint may live under a different domain, path or both depending on the supplier endpoint URL returned by the GET /suppliers.**

        Contains all product details necessary to ingest, map, and sell.
      operationId: 'products'
      parameters:
        - $ref: '#/components/parameters/SupplierId'
      responses:
        '200':
          description: |
            List of products with details.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /suppliers/{supplierId}/availability:
    get:
      tags:
        - Availability
      summary: 'Returns a list of dates and their availability status.'
      description: |
        **WARNING: this endpoint may live under a different domain, path or both depending on the supplier endpoint URL returned by the GET /suppliers.**

        For any dates which are never available for booking, the response MUST exclude those dates entirely.

        If the product's `availabilityType` is `OPENING_HOURS` then the `localDateTimeStart` and `localDateTimeEnd` are the hours of operation. If a product has more than one hours of operation on the same day (e.g. the supplier is open 8-5 but closed for lunch from 12-1) then one availability object MUST be returned for each contiguous range of time for that day.

        The availability `id` value MUST be sent when making a Booking request.

        The `status` field SHOULD be used to infer how frequently your cache should be updated from the Booking Platform. The RECOMMENDED frequency is as follows:

          * `FREESALE`: Always available. Refresh no more than once/week.
          * `AVAILABLE`: Currently available for sale, but has a fixed capacity. Refresh every 12 hours.
          * `LIMITED`: Currently available for sale, but has a fixed capacity and may be sold out soon. Refresh at least once/hour.
          * `SOLD_OUT`: Currently sold out, but additional availability may free up. Refresh no more than once/hour.
          * `CLOSED`: Currently not available for sale, but not sold out (e.g. temporarily on stop-sell) and may be available for sale soon. Refresh no more than once/12 hours.
      operationId: 'availabilityOverview'
      parameters:
        - $ref: '#/components/parameters/SupplierId'
        - $ref: '#/components/parameters/ProductId'
        - $ref: '#/components/parameters/OptionId'
        - $ref: '#/components/parameters/LocalDateStart'
        - $ref: '#/components/parameters/LocalDateEnd'
      responses:
        '200':
          description: |
            List of availability objects with status.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AvailabilityItem'
                example:
                  - id: '28271273-a317-40fc-8f42-79725a7072a3'
                    localDateTimeStart: '2019-10-31T08:30:00Z'
                    localDateTimeEnd: '2019-10-31T10:00:00Z'
                    status: 'AVAILABLE'
                    vacancies: 100
                  - id: '6143d137-fdf6-4da1-a558-20aa93eb55f0'
                    localDateTimeStart: '2019-10-31T12:00:00Z'
                    localDateTimeEnd: '2019-10-31T13:00:00Z'
                    status: 'FREESALE'
                    vacancies: null
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Availability
      summary: 'Returns a list of dates after evaluating the specific Unit and Availability IDs that the customer would like to book.'
      description: |
        **WARNING: this endpoint may live under a different domain, path or both depending on the supplier endpoint URL returned by the GET /suppliers.**

        This request is intended to provide the Booking Platform a complete view of the Unit IDs, Unit quantity, and Availability IDs so that additional restrictions and policies can be validated within the Booking Platform prior to making a Booking. The purpose is to provide a clear and accurate answer to the Reseller about whether the requested booking configuration could be accepted by the Supplier. This is to support complex booking requirements without the Reseller needing to know the details of the restriction (e.g. "must purchase at least 1 adult ticket if a child ticket is purchased").
      operationId: 'availabilityCheck'
      parameters:
        - $ref: '#/components/parameters/SupplierId'
      requestBody:
        $ref: '#/components/requestBodies/AvailabilityCheckRequest'
      responses:
        '200':
          description: |
            List of availability objects with status.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AvailabilityItem'
                example:
                  - id: '28271273-a317-40fc-8f42-79725a7072a3'
                    localDateTimeStart: '2019-10-31T08:30:00Z'
                    localDateTimeEnd: '2019-10-31T10:00:00Z'
                    status: 'AVAILABLE'
                    vacancies: 100
                  - id: '6143d137-fdf6-4da1-a558-20aa93eb55f0'
                    localDateTimeStart: '2019-10-31T12:00:00Z'
                    localDateTimeEnd: '2019-10-31T13:00:00Z'
                    status: 'FREESALE'
                    vacancies: null
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /suppliers/{supplierId}/availability/calendar:
    get:
      tags:
        - Availability
      summary: 'Get a list of dates on which tickets are available'
      description: |
        **WARNING: this endpoint may live under a different domain, path or both depending on the supplier endpoint URL returned by the GET /suppliers.**

        Returns a list of dates (no times) and the number of vacancies. The response MUST only include dates that have vacancies and a minimum range of 31 days MUST be supported.

        This endpoint is intended to support a lightweight way to show a calendar in a user interface containing a one month view with the days where there is no availability greyed out.
      operationId: 'availabilityCalendar'
      parameters:
        - $ref: '#/components/parameters/SupplierId'
        - $ref: '#/components/parameters/ProductId'
        - $ref: '#/components/parameters/OptionId'
        - $ref: '#/components/parameters/LocalDateStart'
        - $ref: '#/components/parameters/LocalDateEnd'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AvailabilityCalendarItem'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /suppliers/{supplierId}/bookings:
    post:
      tags:
        - Bookings
      summary: 'Create a new pending booking.'
      description: |
        **WARNING: this endpoint may live under a different domain, path or both depending on the supplier endpoint URL returned by the GET /suppliers.**

        This creates a new pending booking.

        This call has to be idempotent. To be able to safely retry a call on any network error or timeout, therefore it MUST not fail on retry or create a duplicate booking. The idempotency key is the UUID. A supplier SHOULD verify that a retried request with the same UUID is matching the original booking data, to avoid erroneous clients generating repeating UUIDs and response with the status 400 and ErrorCode 1005 in such case.
      operationId: 'createBooking'
      parameters:
        - $ref: '#/components/parameters/SupplierId'
      requestBody:
        $ref: '#/components/requestBodies/CreateBookingRequest'
      responses:
        '200':
          $ref: '#/components/responses/BookingResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /suppliers/{supplierId}/bookings/{uuid}:
    get:
      tags:
        - Bookings
      summary: 'Gets the current details of an in-progress booking or completed booking.'
      description: |
        **WARNING: this endpoint may live under a different domain, path or both depending on the supplier endpoint URL returned by the GET /suppliers.**

        This returns the current state of any valid booking. This request MAY be made at any point after the initial `createBooking` request is processed successfully and it MUST return the booking object.
      operationId: 'booking'
      parameters:
        - $ref: '#/components/parameters/SupplierId'
        - $ref: '#/components/parameters/Uuid'
      responses:
        '200':
          $ref: '#/components/responses/BookingResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /suppliers/{supplierId}/bookings/{uuid}/extend:
    post:
      tags:
        - Bookings
      summary: 'Extend the hold of an in-progress booking.'
      description: |
        **WARNING: this endpoint may live under a different domain, path or both depending on the supplier endpoint URL returned by the GET /suppliers.**

        This extends the hold of an in-progress booking. The `utcHoldExpiration` MUST NOT be elapsed when this request is sent, otherwise the response MAY show a `status` of `EXPIRED`.
      operationId: 'extendBooking'
      parameters:
        - $ref: '#/components/parameters/SupplierId'
        - $ref: '#/components/parameters/Uuid'
      requestBody:
        $ref: '#/components/requestBodies/ExtendBookingRequest'
      responses:
        '200':
          $ref: '#/components/responses/BookingResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /suppliers/{supplierId}/bookings/{uuid}/confirm:
    post:
      tags:
        - Bookings
      summary: 'Confirm an in-progress booking.'
      description: |
        **WARNING: this endpoint may live under a different domain, path or both depending on the supplier endpoint URL returned by the GET /suppliers.**

        This confirms an in-progress booking. The `utcHoldExpiration` MUST NOT be elapsed when this request is sent, otherwise the response MAY show a `status` of `EXPIRED`.

        This call MUST be idempotent so that a Reseller may retry the request for any network error or timeout. The Booking `uuid` MUST be used to ensure idempotency of the request.
      operationId: 'confirmBooking'
      parameters:
        - $ref: '#/components/parameters/SupplierId'
        - $ref: '#/components/parameters/Uuid'
      requestBody:
        $ref: '#/components/requestBodies/ConfirmBookingRequest'
      responses:
        '200':
          $ref: '#/components/responses/BookingResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /suppliers/{supplierId}/bookings/{uuid}/cancel:
    post:
      tags:
        - Bookings
      summary: 'Either cancel the booking, or expire the hold of an in-progress booking.'
      description: |
        **WARNING: this endpoint may live under a different domain, path or both depending on the supplier endpoint URL returned by the GET /suppliers.**

        This expires the availability hold of an in-progress booking so that the availablity is release for other bookings. This request is a courtesy, however Resellers SHOULD send this in order to ensure proper cleanup of any outstanding holds.

        This call has to be idempotent. To be able to safely retry a call on any network error or timeout, therefore it MUST not fail on retry. The idempotency key is the UUID.
      operationId: 'cancelBooking'
      parameters:
        - $ref: '#/components/parameters/SupplierId'
        - $ref: '#/components/parameters/Uuid'
      requestBody:
        $ref: '#/components/requestBodies/CancelBookingRequest'
      responses:
        '200':
          $ref: '#/components/responses/BookingResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Availability:
      type: object
      required:
        - id
        - localDateTimeStart
        - localDateTimeEnd
      properties:
        id:
          type: string
          description: |
            This MUST be a unique identifier within the scope of the Option.
          example: '28271273-a317-40fc-8f42-79725a7072a3'
        localDateTimeStart:
          type: string
          description: |
            This MUST be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant date and time.
          format: date-time
          example: '2019-10-31T08:30:00Z'
        localDateTimeEnd:
          type: string
          description: |
            This MUST be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant date and time.
          format: date-time
          example: '2019-10-31T10:00:00Z'
    AvailabilityCalendarItem:
      type: object
      required:
        - localDate
        - status
      properties:
        localDate:
          type: string
          description: |
            This MUST be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant date.
          format: date
          example: '2019-10-31'
        status:
          $ref: '#/components/schemas/AvailabilityStatus'
        vacancies:
          type: integer
          description: |
            This SHOULD NOT be returned when `status` is `FREESALE`. This SHOULD be a shared pool for all Unit types in the Option. If availability is tracked per-Unit then this value MUST be equal to the available quantity for the Unit that has the most remaining.
          example: 100
          minimum: 0
    AvailabilityItem:
      allOf:
        - $ref: '#/components/schemas/Availability'
        - type: object
          required:
            - status
          properties:
            status:
              $ref: '#/components/schemas/AvailabilityStatus'
            vacancies:
              type: integer
              description: |
                This SHOULD NOT be returned when `status` is `FREESALE`. This SHOULD be a shared pool for all Unit types in the Option. If availability is tracked per-Unit then this value MUST be equal to the available quantity for the Unit that has the most remaining.
              example: 100
              minimum: 0
    AvailabilityStatus:
      type: string
      description: |
        This represents whether the availability in this configuration is currently bookable. The values have the following meanings:

        * `FREESALE`: Always available.
        * `AVAILABLE`: Currently available for sale, but has a fixed capacity.
        * `LIMITED`: Currently available for sale, but has a fixed capacity and may be sold out soon.
        * `SOLD_OUT`: Currently sold out, but additional availability may free up.
        * `CLOSED`: Currently not available for sale, but not sold out (e.g. temporarily on stop-sell) and may be available for sale soon.
      enum:
        - FREESALE
        - AVAILABLE
        - LIMITED
        - SOLD_OUT
        - CLOSED
      example: 'AVAILABLE'
    AvailabilityType:
      type: string
      description: |
        This indicates whether the Product redemption is valid only for a specific start time (e.g. a guided tour) or valid any time during normal business hours.
      enum:
        - START_TIME
        - OPENING_HOURS
      example: 'START_TIME'
    Booking:
      type: object
      required:
        - uuid
        - status
        - cancellable
        - productId
        - optionId
        - availability
        - contact
        - deliveryMethods
        - unitItems
      properties:
        uuid:
          type: string
          format: uuid
          description: |
            This is a randomly-generated UUID that MUST be tracked by both the Reseller and Booking Platform for locating this record.
          example: 'f149068e-300e-452a-a856-3f091239f1d7'
        resellerReference:
          type: string
          description: |
            An OPTIONAL tracking reference for the Reseller that SHOULD be tracked by the Booking Platform. This MUST be returned if the value was provided in the request body.
          example: '001-002'
        supplierReference:
          type: string
          description: |
            An OPTIONAL tracking reference for the Supplier that SHOULD be tracked by the Reseller.
          example: 'ABC-123'
        status:
          $ref: '#/components/schemas/Status'
        cancellable:
          type: boolean
          description: |
            Indicates whether the booking is cancellable right now
          example: true
        utcHoldExpiration:
          type: string
          format: date-time
          description: |
            This MUST be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant date and time. The value represents the time at which the availability hold will be released. This SHOULD be equivalent to the time calculated by adding `holdExpirationMinutes` to the current UTC time but MAY be either earlier or later than the requested duration.
          example: '2019-10-31T08:30:00Z'
        utcConfirmedAt:
          type: string
          format: date-time
          description: |
            This MUST be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant date and time. The value represents the time at which the booking was confirmed (either automatically by the Booking Platform or manually by the Supplier).
          example: '2019-10-31T08:30:00Z'
        utcDeliveredAt:
          type: string
          format: date-time
          description: |
            This MUST be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant date and time. The value represents the time at whcih the VOUCHER was delivered.
          example: '2019-10-31T08:30:00Z'
        refreshFrequency:
          $ref: '#/components/schemas/RefreshFrequency'
        productId:
          type: string
          description: |
            A valid product ID that matches the `id` returned from `GET /suppliers/{supplierId}/products`.
          example: 'adult'
        optionId:
          type: string
          description: |
            A valid option ID that matches the `id` returned from `GET /suppliers/{supplierId}/products`.
          example: 'LR1-01'
        availability:
          $ref: '#/components/schemas/Availability'
        contact:
          $ref: '#/components/schemas/Contact'
        deliveryMethods:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryMethod'
          minItems: 1
          maxItems: 2
        voucher:
          $ref: '#/components/schemas/Ticket'
        unitItems:
          type: array
          items:
            $ref: '#/components/schemas/UnitItemTicket'
          minItems: 1
        cancellationRequest:
          $ref: '#/components/schemas/CancellationRequest'
    CancellationRequest:
      type: object
      required:
        - reason
        - reasonDetails
        - status
        - refund
        - utcRequestedAt
        - utcConfirmedAt
        - utcResolvedAt
      properties:
        reason:
          $ref: '#/components/schemas/CancelReason'
        reasonDetails:
          type: string
          description: |
            This field provides additional details about the reason for the cancellation request. It may include information from the customer, supplier, or support agent about the reason for the cancellation (especially in the case of requesting a cancellation outside of the normal policy which may require manual approval from the supplier).
          example: 'Child came down with the flu the day before the activity.'
        status:
          $ref: '#/components/schemas/Status'
        refund:
          $ref: '#/components/schemas/Refund'
        utcRequestedAt:
          type: string
          format: date-time
          description: |
            This MUST be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant date and time. The value represents the time at which the cancellation request was originally started. This timestamp MUST be used for any validation against a cancellation policy. This is important because there may be some delay in confirming this cancellation request during the 2-phase workflow which could finish just after the cancellation policy cutoff has elapsed.
          example: '2019-10-31T08:30:00Z'
        utcConfirmedAt:
          type: string
          format: date-time
          nullable: true
          description: |
            This MUST be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant date and time. The value represents the time at which the cancellation request was confirmed by the Reseller.
          example: '2019-10-31T08:30:00Z'
        utcResolvedAt:
          type: string
          format: date-time
          nullable: true
          description: |
            This MUST be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant date and time. The value represents the time at which the cancellation was confirmed. This will typically be the same as `utcConfirmedAt` however if the cancellation request required manual approval from the Supplier, it may be different.
          example: '2019-10-31T08:30:00Z'
    CancelReason:
      type: string
      enum:
        - CUSTOMER
        - SUPPLIER
        - FRAUD
        - OTHER
      description: |
        This value indicates the reason that the cancellation request was sent.

        * `CUSTOMER` is the most common and indicates that the customer requested the cancellation.
        * `SUPPLIER` indicates that the supplier requested the cancellation (possibly due to bad weather or other unexpected circumstances).
        * `FRAUD` indicates that the booking cancellation is being requested by the Reseller because it has been determined the booking was fraudulent.
        * `OTHER` indicates that the cancellation reason does not fall into one of these categories. This SHOULD be used only in rare circumstances.
      example: 'CUSTOMER_REQUESTED'
    Capability:
      type: object
      required:
        - id
        - revision
        - required
      properties:
        id:
          type: string
          description: |
            This MUST be a unique identifier within the scope of the OCTo specification. Officially adopted capabilities will be identified only by the name of the capability but any capabilities that are specific to a particular partner MUST be prefixed with that partner's identifier and separated from the capability name with a `/`.
          example: 'api.my-booking-platform.com/dynamic-pricing'
        revision:
          type: integer
          description: |
            This represents which revision of the capability is supported. This is not a version numbers and therefore there is no implied version compatibility like you would have with a semantic version, therefore if multiple revisions are supported, then one Capability object should be returned for each revision that is supported.
          example: 2
        required:
          type: boolean
          description: |
            This indicates whether the capability is merely supported or strictly required. Resellers that don't support the capability or specific revision will use this flag to filter out products they are unable to support.
          example: true
    Contact:
      type: object
      required:
        - fullName
        - emailAddress
        - locales
      properties:
        fullName:
          type: string
          description: |
            The full name of the lead traveller.
          example: 'Mr. Traveller'
        emailAddress:
          type: string
          format: email
          description: |
            The contact email of the lead traveller.
          example: 'traveller@fake.com'
        phoneNumber:
          type: string
          description: |
            The contact phone number of the lead traveller.
          example: '+1 555-555-1212'
        locales:
          type: array
          items:
            type: string
            description: |
              This MUST be a valid [BCP 47](https://tools.ietf.org/html/bcp47) [RFC 5646](https://tools.ietf.org/html/rfc5646) [RFC 4647](https://tools.ietf.org/html/rfc4647) language tag.
            example: 'en-GB'
          example:
            - en-GB
            - en-US
            - en
          minItems: 0
        country:
          type: string
          description: |
            This MUST be a valid [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code.
          example: 'GB'
    DeliveryFormat:
      type: string
      enum:
        - PDF_URL
        - QRCODE
        - AZTEC
        - CODE128
        - CODE39
      description: |
        This indicates the format for the `deliveryValue` so that it can be parsed or encoded correctly.
      example: 'CODE39'
    DeliveryMethod:
      type: string
      enum:
        - TICKET
        - VOUCHER
      description: |
        A value of `TICKET` indicates that there will be one `deliveryValue` for each ticket in the Booking while a value of `VOUCHER` indicates that there will be one `deliveryValue` that is shared among all tickets in the Booking.
      example: 'VOUCHER'
    DeliveryOption:
      type: object
      required:
        - deliveryFormat
        - deliveryValue
      properties:
        deliveryFormat:
          $ref: '#/components/schemas/DeliveryFormat'
        deliveryValue:
          type: string
          description: |
            Represents the value for the voucher or ticket that should be used. If the `deliveryFormat` is `PDF_URL` then this value MUST be a valid [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) that resolves to a `PDF` resource. For any other `deliveryFormat` this value MUST be encoded according to the `deliveryFormat` value.
          example: '01234567890'
    ExtendReason:
      type: string
      enum:
        - FRAUD_CHECK
        - CUSTOMER_REQUESTED
        - OTHER
      description: |
        This indicates the reason for extending the booking hold.

        * `FRAUD_CHECK` is the most common scenario where additional time is required to ensure that the booking is not being made using fraudulent payment information.
        * `CUSTOMER_REQUESTED` is intended for scenarios where the customer is actively completing the checkout process but requires some additional time to complete. The Reseller SHOULD try to ensure that customers may only extend their booking once.
        * `OTHER` can be used in other unusual circumstances but SHOULD not be abused to maintain a hold without good reason. If this value is specified the Reseller SHOULD provide `reasonDetails` to explain the justification.
      example: 'FRAUD_CHECK'
    Product:
      type: object
      required:
        - id
        - internalName
        - locale
        - timeZone
        - instantConfirmation
        - instantDelivery
        - availabilityType
        - deliveryFormats # confirm
        - deliveryMethods # confirm
        - redemptionMethod
        - options
      properties:
        id:
          type: string
          description: |
            This MUST be unique within the scope of the Supplier.
          example: '0001'
        internalName:
          type: string
          description: |
            This SHOULD be a friendly name for the Product to facilitate easier identification. It MUST NOT be shown to the customer.
          example: 'Morning tour'
        reference:
          type: string
          description: |
            This is an internal reference identifier that the Supplier wishes to use. It MAY be non-unique.
          example: 'LR1-01'
        locale:
          type: string
          description: |
            This MUST be a valid [BCP 47](https://tools.ietf.org/html/bcp47) [RFC 5646](https://tools.ietf.org/html/rfc5646) [RFC 4647](https://tools.ietf.org/html/rfc4647) language tag.
          example: 'en-GB'
        timeZone:
          type: string
          description: |
            This MUST be a valid database name from the ICANN [tz database](https://en.wikipedia.org/wiki/Tz_database). Any calculation of UTC offset or UTC DTC offset MUST use the correct offset from this database.
          example: 'Europe/London'
        instantConfirmation:
          type: boolean
          description: |
            This indicates whether the Reseller can expect an immediate confirmation of whether the Supplier has accepted the booking. If `false` then the Reseller MUST be able to delay confirmation to the customer while waiting for the Supplier to accept or reject the Booking.

            When `instantConfirmation` is set to `false` one should expect created bookings to first get into a `PENDING` state.
          example: true
        instantDelivery:
          type: boolean
          description: |
            This indicates whether the Reseller can expect immediate delivery of the customer's tickets. If `false` then the Reseller MUST be able to delay delivery of the tickets to the customer.
          example: true
        availabilityType:
          $ref: '#/components/schemas/AvailabilityType'
        deliveryFormats:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryFormat'
          description: |
            This MAY contain more than one value if some Options or Units under this Product will use different delivery formats. The Reseller MUST be able to support all of the specified formats in order to sell this Product.
          example:
            - PDF_URL
            - CODE39
        deliveryMethods:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryMethod'
          description: |
            A product MAY support both types of delivery methods.
          example:
            - TICKET
            - VOUCHER
        redemptionMethod:
          $ref: '#/components/schemas/RedemptionMethod'
        capabilities:
          type: array
          items:
            $ref: '#/components/schemas/Capability'
          minItems: 0
          example:
            - id: 'dynamic-pricing'
              revision: 1
              required: true
            - id: 'api.my-booking-platform.com/dynamic-pricing'
              revision: 2
              required: false
        options:
          type: array
          items:
            $ref: '#/components/schemas/ProductOption'
          minItems: 1
          example:
            - id: '0001'
              internalName: 'Morning'
              reference: 'LR1-01'
              units:
                - id: 'adult'
                  internalName: 'Adult'
                  reference: 'LR1-01-01'
                  type: 'ADULT'
                - id: '0001-0001-child'
                  internalName: 'Child'
                  reference: 'LR1-01-02'
                  type: 'CHILD'
            - id: '0002'
              internalName: 'Afternoon'
              reference: 'LR1-02'
              units:
                - id: 'adult'
                  internalName: 'Adult'
                  reference: 'LR1-01-01'
                  type: 'ADULT'
                - id: '0001-0001-child'
                  internalName: 'Child'
                  reference: 'LR1-01-02'
                  type: 'CHILD'
    ProductOption:
      type: object
      required:
        - id
        - internalName
        - units
      properties:
        id:
          type: string
          description: |
            This MUST be a unique identifier within the scope of the Product.
          example: '0001'
        internalName:
          type: string
          description: |
            This SHOULD be a friendly name for the Option to facilitate easier identification. It MUST NOT be shown to the customer.
          example: 'Morning'
        reference:
          type: string
          description: |
            This is an internal reference identifier that the Supplier wishes to use. It MAY be non-unique.
          example: 'LR1-01'
        units:
          type: array
          items:
            $ref: '#/components/schemas/Unit'
          minItems: 1
          example:
            - id: 'adult'
              internalName: 'Adult'
              reference: 'LR1-01-01'
              type: 'ADULT'
            - id: '0001-0001-child'
              internalName: 'Child'
              reference: 'LR1-01-02'
              type: 'CHILD'
    RedemptionMethod:
      type: string
      description: |
        This indicates the redemption requirements for the customer. A value of `MANIFEST` indicates that the customer MUST provide a form of identification to redeem and as such a printed or digital copy of the ticket is OPTIONAL. A value of `DIGITAL` indicates that the customer MUST provide a copy of the ticket but MAY be digital or printed. A value of `PRINT` indicates that the customer MUST provide a printed copy of the ticket (this is typically only used when the Supplier must retain the printed copy for their records).
      enum:
        - MANIFEST
        - DIGITAL
        - PRINT
      example: 'DIGITAL'
    RefreshFrequency:
      type: string
      enum:
        - HOURLY
        - DAILY
      description: |
        This is the RECOMMENDED refresh interval for the Reseller and SHOULD be used by the Reseller to control the frequency at which they make a `getBooking` request for the following scenarios:

        * To see if a booking has changed out of a `PENDING` status into `CONFIRMED` or `REJECTED`.
        * To see if a booking has had any new Vouchers or Tickets delivered for the booking.
        * To see if a booking has changed from `CONFIRMED` to `CANCELLED` in the event of a supplier-initiated cancellation.
        * To see if a booking has an updated `utcRedeemedAt`/`utcResolvedAt` value for the Voucher or any of the Tickets.
      example: 'HOURLY'
    Refund:
      type: string
      enum:
        - FULL
        - PARTIAL
        - NONE
      description: |
        This value indicates the expected refund from the Supplier.
        * `FULL` indicates that the Supplier has fully refunded the booking and will not be paid by the Reseller for this booking. This is the expected state when a valid cancellation request is made before any cancellation cutoff policy or when a Supplier approves a cancellation request that was made after the cutoff.
        * `PARTIAL` indicates that the Supplier has agreed to partially refund the customer. This may be due to a cancellation policy that grants a partial refund or because the Supplier has agreed to partially refund the customer when the cancellation policy would otherwise have not allowed any refund.
        * `NONE` indicates that no refund will be given by the Supplier. The customer may still be refunded by the Reseller but the Supplier MUST still be paid for this booking.
      example: 'FULL'
    Status:
      type: string
      enum:
        - ON_HOLD
        - EXPIRED
        - PENDING
        - REJECTED
        - CONFIRMED
        - CANCELLED
      description: |
        After a successful `createBooking` request, the `status` MUST be `ON_HOLD`.

        After a successful `confirmBooking` request, the `status` MUST be `CONFIRMED`.

        After a successful `confirmCancellation` request, the `status` MUST be `CANCELLED`.

        Following are the only valid Booking flow status transitions:

        * New Booking -> `REJECTED`
        * New Booking -> `ON_HOLD` -> `EXPIRED`
        * New Booking -> `ON_HOLD` -> `CONFIRMED`
        * New Booking -> `ON_HOLD` -> `PENDING` -> `REJECTED`
        * New Booking -> `ON_HOLD` -> `PENDING` -> `CONFIRMED`

        The `PENDING` status MAY appear only for products with the `instantConfirmation` property set to `false`. Poll the /bookings endpoint for status changes.

        Following are the only valid Cancellation flow status transitions:

        * `CONFIRMED` -> `CANCELLED`
        * `ON_HOLD` -> `EXPIRED`
      example: 'ON_HOLD'
    Supplier:
      type: object
      required:
        - id
        - name
        - endpoint
        - contact
      properties:
        id:
          type: string
          description: |
            This MUST be unique within the scope of the Booking Platform.
          example: '0001'
        name:
          type: string
          description: |
            Common name for the supplier that may be displayed to the customer.
          example: 'Acme Tour Co.'
        endpoint:
          type: string
          description: |
            This is the base URL that will be prepended to ALL other paths. The value SHOULD NOT contain a trailing `/`.
          format: uri
          example: 'https://api.my-booking-platform.com/v1'
        contact:
          $ref: '#/components/schemas/SupplierContact'
    SupplierContact:
      type: object
      description: |
        Contact details for the supplier.
      required:
        - email
      properties:
        website:
          type: string
          description: |
            This SHOULD be the website of the Supplier that is separate from the Booking Platform but MAY be a unique destination within the Booking Platform about the Supplier.
          format: url
          example: 'https://acme-tours.co.fake'
        email:
          type: string
          description: |
            This SHOULD be the email support contact for the Supplier. This information MAY be provided to the customer.
          format: email
          example: 'info@acme-tours.co.fake'
        telephone:
          type: string
          description: |
            This SHOULD be the phone support contact for the Supplier. This information MAY be provided to the customer.
          example: '+1 888-555-1212'
        address:
          type: string
          description: |
            This SHOULD be the mail address support contact for the Supplier. This information MAY be provided to the customer.
          example: '123 Main St, Anytown USA'
    Ticket:
      type: object
      required:
        - deliveryOptions
        - redemptionMethod
      properties:
        deliveryOptions:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryOption'
        redemptionMethod:
          $ref: '#/components/schemas/RedemptionMethod'
        utcDeliveredAt:
          type: string
          format: date-time
          description: |
            This MUST be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant date and time. The value represents the time at which the voucher was made available to the customer by the Supplier. This will typically be the same as `utcConfirmedAt`.
          example: '2019-10-31T08:30:00Z'
        utcRedeemedAt:
          type: string
          format: date-time
          description: |
            This MUST be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant date and time. The value represents the time at which the customer redeemed this voucher.
          example: '2019-10-31T08:30:00Z'
    Unit:
      type: object
      required:
        - id
        - internalName
        - type
      properties:
        id:
          type: string
          description: |
            This MUST be a unique identifier within the scope of the Option.
          example: 'youth_10_17'
        internalName:
          type: string
          description: |
            This SHOULD be a friendly name for the Unit to facilitate easier identification. It MUST NOT be shown to the customer.
          example: 'Youth (Summer)'
        reference:
          type: string
          description: |
            This is an internal reference identifier that the Supplier wishes to use. It MAY be non-unique.
          example: 'LR1-01-new'
        type:
          $ref: '#/components/schemas/UnitType'
    UnitItem:
      type: object
      required:
        - uuid
        - unitId
      properties:
        uuid:
          type: string
          description: |
            This is a randomly-generated UUID that MUST be tracked by both the Reseller and Booking Platform for locating this record.
          example: '6be0409f-181e-4520-acc1-cc6791896859'
        unitId:
          type: string
          description: |
            A valid unit ID that matches the `id` returned from `GET /suppliers/{supplierId}/products`.
          example: 'adult'
        resellerReference:
          type: string
          description: |
            An OPTIONAL tracking reference for the Reseller that SHOULD be tracked by the Booking Platform. This MUST be returned if the value was provided in the request body.
          example: '001-002'
    UnitItemTicket:
      allOf:
        - $ref: '#/components/schemas/UnitItem'
        - type: object
          properties:
            supplierReference:
              type: string
              description: |
                An OPTIONAL tracking reference for the Supplier that SHOULD be tracked by the Reseller.
              example: 'ABC-123'
            ticket:
              $ref: '#/components/schemas/Ticket'
    UnitQuantity:
      type: object
      required:
        - unitId
        - quantity
      properties:
        unitId:
          type: string
          description: |
            A valid unit ID that matches the `id` returned from `GET /suppliers/{supplierId}/products`.
            example: 'adult'
        quantity:
          type: integer
          description: |
            The total number of this unit that the customer wants to purchase.
          example: 2
    UnitType:
      type: string
      description: |
        This is the base unit type for this unit definition. A value of `TRAVELLER` MUST only be used in replacement of `ADULT`, `CHILD`, `INFANT`, `YOUTH`, `STUDENT`, or `SENIOR`.
      enum:
        - ADULT
        - CHILD
        - INFANT
        - YOUTH
        - STUDENT
        - SENIOR
        - TRAVELLER
        - RESOURCE
        - OTHER
      example: 'YOUTH'
  responses:
    BadRequest:
      description: |
        Invalid request (e.g. missing required parameters, invalid model, missing `Date` header, etc.).
    Unauthorized:
      description: |
        Missing `Authorization` header or key could not be validated.
    Forbidden:
      description: |
        The `Authorization` header was validated but the requestor does not have the correct permissions to access the requested resource or perform the requested operation.
    NotFound:
      description: |
        Invalid URI path requested.
    InternalServerError:
      description: |
        An unknown error occurred and the server cannot respond in a sensible way. The response may not include a valid error object if one could not be generated.
    BookingResponse:
      description: |
        A complete representation of the current booking booking status.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Booking'
  parameters:
    LocalDateStart:
      name: 'localDateStart'
      in: query
      description: |
        This MUST be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant date. The start of the date range MUST be treated as inclusive of this date when generating the response.
      required: true
      schema:
        type: string
        format: date
    LocalDateEnd:
      name: 'localDateEnd'
      in: query
      description: |
        This MUST be an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant date. The end of the date range MUST be treated as exclusive of this date when generating the response.
      required: true
      schema:
        type: string
        format: date
    OptionId:
      name: 'optionId'
      in: query
      description: |
        A valid option ID that matches the `id` returned from `GET /suppliers/{supplierId}/products`.
      required: true
      schema:
        type: string
        format: string
    ProductId:
      name: 'productId'
      in: query
      description: |
        A valid product ID that matches the `id` returned from `GET /suppliers/{supplierId}/products`.
      required: true
      schema:
        type: string
        format: string
    SupplierId:
      name: 'supplierId'
      in: path
      description: |
        A valid supplier ID that matches the `id` returned from `GET /suppliers`.
      required: true
      schema:
        type: string
        format: string
    Uuid:
      name: 'uuid'
      in: path
      description: |
        A valid booking UUID that matches the `uuid` sent during the initial `POST /suppliers/{supplierId}/bookings`
      required: true
      schema:
        type: string
        format: uuid
  requestBodies:
    AvailabilityCheckRequest:
      required: true
      description: |
        This MUST include all units that the customer is attempting to reserve and SHOULD include all possible availability IDs that the customer may be interested in reserving.
      content:
        application/json:
          schema:
            type: object
            required:
              - productId
              - optionId
              - availabilityIds
              - units
            properties:
              productId:
                type: string
                description: |
                  A valid product ID that matches the `id` returned from `GET /suppliers/{supplierId}/products`.
                example: 'adult'
              optionId:
                type: string
                description: |
                  A valid option ID that matches the `id` returned from `GET /suppliers/{supplierId}/products`.
                example: 'LR1-01'
              availabilityIds:
                type: array
                items:
                  type: string
                  description: |
                    A valid list of availability IDs that matches the `id` returned from `GET /availability`.
                  example: '28271273-a317-40fc-8f42-79725a7072a3'
                example:
                  - '28271273-a317-40fc-8f42-79725a7072a3'
                  - '6143d137-fdf6-4da1-a558-20aa93eb55f0'
                minItems: 1
              units:
                type: array
                items:
                  $ref: '#/components/schemas/UnitQuantity'
                example:
                  - id: 'adult'
                    quantity: 2
                  - id: 'child'
                    quantity: 1
                minItems: 1
    CreateBookingRequest:
      required: true
      description: |
        This MUST include all unitItems that the customer wants to book.
      content:
        application/json:
          schema:
            type: object
            required:
              - uuid
              - productId
              - optionId
              - availabilityId
              - unitItems
            properties:
              uuid:
                type: string
                format: uuid
                description: |
                  This UUID is generated for the initial `createBooking` request and MUST never change. This value MUST be tracked by both the Reseller and Booking Platform for locating this record.
                example: '7df49d62-57ad-44be-8373-e4c2fe7e63fe'
              resellerReference:
                type: string
                description: |
                  An OPTIONAL tracking reference for the Reseller that SHOULD be tracked by the Booking Platform. This MUST be returned if the value was provided in the request body.
                example: '001-002'
              productId:
                type: string
                description: |
                  A valid product ID that matches the `id` returned from `GET /suppliers/{supplierId}/products`.
                example: 'adult'
              optionId:
                type: string
                description: |
                  A valid option ID that matches the `id` returned from `GET /suppliers/{supplierId}/products`.
                example: 'LR1-01'
              availabilityId:
                type: string
                description: |
                  A valid availability ID that matches the `id` returned from `GET /suppliers/{supplierId}/availability`.
                example: '28271273-a317-40fc-8f42-79725a7072a3'
              unitItems:
                type: array
                items:
                  $ref: '#/components/schemas/UnitItem'
                minItems: 1
              holdExpirationMinutes:
                type: integer
                description: |
                  This is the duration that the Reseller would like the product inventory to be temporarily held while the booking is completed. The Booking Platform SHOULD reserve the inventory for at least this duration but MAY reserve for a shorter period of time. The exact hold expiration time will be returned in the response.
                example: 30
    ExtendBookingRequest:
      required: true
      description: |
        This MUST include the proper `reason` for requesting the extension and MUST NOT be abused to keep availability reserved due to processing delays by the Reseller.
      content:
        application/json:
          schema:
            type: object
            required:
              - reason
              - holdExpirationMinutes
            properties:
              reason:
                $ref: '#/components/schemas/ExtendReason'
              reasonDetails:
                type: string
                description: |
                  This provides additional details behind the reason for requesting the extension and SHOULD be provided in all cases, but especially if the `reason` given is `OTHER`.
                example: 'Manual fraud review with 2-hour SLA.'
              holdExpirationMinutes:
                type: integer
                description: |
                  This is the duration that the Reseller would like the product inventory hold to be extended while the booking is completed. The Booking Platform SHOULD extend the hold on the inventory for at least this duration from the time of the request but MAY reserve for a shorter period of time. The exact hold expiration time will be returned in the response.
                example: 120
    ConfirmBookingRequest:
      required: true
      description: |
        This confirms an in-progress booking and MUST be sent before the `utcHoldExpiration` has elapsed.
      content:
        application/json:
          schema:
            type: object
            required:
              - contact
            properties:
              resellerReference:
                type: string
                description: |
                  An OPTIONAL tracking reference for the Reseller that SHOULD be tracked by the Booking Platform. This MUST be returned if the value was provided in the request body.
                example: '001-002'
              contact:
                $ref: '#/components/schemas/Contact'
    CancelBookingRequest:
      required: true
      description: |
        This request will release the inventory hold on an in-progress booking or cancel a completed booking. It is RECOMMENDED that this request be sent if the customer fails to complete their booking, in order to release the inventory for other customers. It is also RECOMMENDED that this request be sent for a completed booking even if no refund is expected so that the Supplier can attempt to sell the unused inventory to another customer.
      content:
        application/json:
          schema:
            type: object
            required:
              - reason
              - reasonDetails
            properties:
              reason:
                $ref: '#/components/schemas/CancelReason'
              reasonDetails:
                type: string
                description: |
                  This field provides additional details about the reason for the cancellation request. It may include information from the customer, supplier, or support agent about the reason for the cancellation (especially in the case of requesting a cancellation outside of the normal policy which may require manual approval from the supplier).
                example: 'Child came down with the flu the day before the activity.'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Bearer {apiKey}

security:
  - bearerAuth: []

tags:
  - name: Suppliers
  - name: Products
  - name: Availability
  - name: Bookings

externalDocs:
  description: OCTo Home
  url: http://octospec.com/
